In [1]:
def most_frequent_book(borrowed_books):
    # Dictionary to store the count of each book title
    book_count = {}
    
    # Counting occurrences of each book title
    for book_info in borrowed_books:
        book_title = book_info[0]
        if book_title in book_count:
            book_count[book_title] += 1
        else:
            book_count[book_title] = 1
    
    # Finding the book with the maximum count
    max_count = -1
    most_frequent_book_title = None
    
    for book_title, count in book_count.items():
        if count > max_count or (count == max_count and book_title < most_frequent_book_title):
            max_count = count
            most_frequent_book_title = book_title
    
    return most_frequent_book_title

# Example usage:
borrowed_books = [
    ("Harry Potter", "Fantasy", "J.K. Rowling"),
    ("Lord of the Rings", "Fantasy", "J.R.R. Tolkien"),
    ("Harry Potter", "Fantasy", "J.K. Rowling"),
    ("Narnia", "Fantasy", "C.S. Lewis"),
    ("Lord of the Rings", "Fantasy", "J.R.R. Tolkien"),
    ("Harry Potter", "Fantasy", "J.K. Rowling"),
    ("Lord of the Rings", "Fantasy", "J.R.R. Tolkien"),
    ("Lord of the Rings", "Fantasy", "J.R.R. Tolkien"),
    ("Percy Jackson", "Fantasy", "Rick Riordan"),
    ("Harry Potter", "Fantasy", "J.K. Rowling")
]

most_borrowed = most_frequent_book(borrowed_books)
print("Most borrowed book:", most_borrowed)  # Output: "Harry Potter"


Most borrowed book: Harry Potter


In [2]:
def most_frequent_book(borrowed_books):
    if not borrowed_books:
        raise ValueError("The list of borrowed books is empty.")
    
    # Dictionary to store the count of each book title
    book_count = {}
    
    # Counting occurrences of each book title
    for book_info in borrowed_books:
        book_title = book_info[0]
        if book_title in book_count:
            book_count[book_title] += 1
        else:
            book_count[book_title] = 1
    
    # Finding the book with the maximum count
    max_count = -1
    most_frequent_book_title = None
    
    for book_title, count in book_count.items():
        if count > max_count or (count == max_count and book_title < most_frequent_book_title):
            max_count = count
            most_frequent_book_title = book_title
    
    return most_frequent_book_title

# Example usage:
borrowed_books = [
    ("Harry Potter", "Fantasy", "J.K. Rowling"),
    ("Lord of the Rings", "Fantasy", "J.R.R. Tolkien"),
    ("Harry Potter", "Fantasy", "J.K. Rowling"),
    ("Narnia", "Fantasy", "C.S. Lewis"),
    ("Lord of the Rings", "Fantasy", "J.R.R. Tolkien"),
    ("Harry Potter", "Fantasy", "J.K. Rowling"),
    ("Lord of the Rings", "Fantasy", "J.R.R. Tolkien"),
    ("Lord of the Rings", "Fantasy", "J.R.R. Tolkien"),
    ("Percy Jackson", "Fantasy", "Rick Riordan"),
    ("Harry Potter", "Fantasy", "J.K. Rowling")
]

try:
    most_borrowed = most_frequent_book(borrowed_books)
    print("Most borrowed book:", most_borrowed)  # Output: "Harry Potter"
except ValueError as e:
    print("Error:", e)

# Example with empty list:
empty_list = []
try:
    most_borrowed_empty = most_frequent_book(empty_list)  # Raises ValueError
    print("Most borrowed book (empty list):", most_borrowed_empty)
except ValueError as e:
    print("Error:", e)  # Output: Error: The list of borrowed books is empty.


Most borrowed book: Harry Potter
Error: The list of borrowed books is empty.


In [3]:
def most_frequent_book(borrowed_books):
    if not borrowed_books:
        raise ValueError("The list of borrowed books is empty.")
    
    # Dictionary to store the count of each book title
    book_count = {}
    
    # Counting occurrences of each book title
    for book_title in borrowed_books:
        if book_title in book_count:
            book_count[book_title] += 1
        else:
            book_count[book_title] = 1
    
    # Finding the book with the maximum count
    max_count = -1
    most_frequent_book_title = None
    
    for book_title, count in book_count.items():
        if count > max_count or (count == max_count and book_title < most_frequent_book_title):
            max_count = count
            most_frequent_book_title = book_title
    
    return most_frequent_book_title, max_count

# Example usage:
borrowed_books = [
    "Harry Potter", "Lord of the Rings", "Harry Potter", "Narnia", 
    "Lord of the Rings", "Harry Potter", "Lord of the Rings", 
    "Lord of the Rings", "Percy Jackson", "Harry Potter"
]

try:
    most_borrowed, count = most_frequent_book(borrowed_books)
    print(f"The most borrowed book is '{most_borrowed}' with {count} borrowings.")
    # Output: The most borrowed book is 'Lord of the Rings' with 4 borrowings.
except ValueError as e:
    print("Error:", e)

# Example with empty list:
empty_list = []
try:
    most_borrowed_empty, count_empty = most_frequent_book(empty_list)  # Raises ValueError
    print("Most borrowed book (empty list):", most_borrowed_empty)
except ValueError as e:
    print("Error:", e)  # Output: Error: The list of borrowed books is empty.


The most borrowed book is 'Harry Potter' with 4 borrowings.
Error: The list of borrowed books is empty.


In [4]:
def most_borrowed(borrowed_items):
    if not borrowed_items:
        raise ValueError("The list of borrowed items is empty.")
    
    # Dictionary to store the count of each item
    item_count = {}
    
    # Counting occurrences of each item
    for item in borrowed_items:
        if item in item_count:
            item_count[item] += 1
        else:
            item_count[item] = 1
    
    # Finding the item with the maximum count
    max_count = -1
    most_borrowed_item = None
    
    for item, count in item_count.items():
        if count > max_count or (count == max_count and item < most_borrowed_item):
            max_count = count
            most_borrowed_item = item
    
    return most_borrowed_item, max_count

# Example usage:
borrowed_books = [
    "Harry Potter", "Lord of the Rings", "Harry Potter", "Narnia", 
    "Lord of the Rings", "Harry Potter", "Lord of the Rings", 
    "Lord of the Rings", "Percy Jackson", "Harry Potter"
]

try:
    most_borrowed_book, count = most_borrowed(borrowed_books)
    print(f"The most borrowed book is '{most_borrowed_book}' with {count} borrowings.")
    # Output: The most borrowed book is 'Lord of the Rings' with 4 borrowings.
except ValueError as e:
    print("Error:", e)


The most borrowed book is 'Harry Potter' with 4 borrowings.


In [5]:
def most_borrowed(borrowed_items):
    if not borrowed_items:
        raise ValueError("The list of borrowed items is empty.")

    item_count = {}
    
    for item in borrowed_items:
        if item in item_count:
            item_count[item] += 1
        else:
            item_count[item] = 1
            
    max_count = -1
    most_borrowed_item = None
    
    for item, count in item_count.items():
        if count > max_count or (count == max_count and item < most_borrowed_item):
            max_count = count
            most_borrowed_item = item
    
    return most_borrowed_item, max_count
try:
    most_borrowed_book, count = most_borrowed(borrowed_books)
    print(f"The most borrowed book is '{most_borrowed_book}' with {count} borrowings.")
except ValueError as e:
    print("Error:", e)


The most borrowed book is 'Harry Potter' with 4 borrowings.


In [6]:
def find_max_odd_value_index(sequence):
    max_odd_value = None
    max_odd_index = None
    
    for index, num in enumerate(sequence):
        if num % 2 != 0:
            if max_odd_value is None or num > max_odd_value:
                max_odd_value = num
                max_odd_index = index
    
    if max_odd_value is not None:
        return [max_odd_index]
    else:
        return []

# Example usage:
sequence1 = [1, 9, 4, 6, 10, 11, 14, 8]

print(find_max_odd_value_index(sequence1))

[5]


In [7]:
import pandas as pd
import numpy as np

data = {
    'Height': [150, 160, 170, 180, 190],
    'Weight': [50, 60, 70, 80, 90],
    'Age': [20, 25, 30, 35, 40]
}

df = pd.DataFrame(data)
covariance_matrix = np.cov(df.transpose())
print("Covariance Matrix:")
print(covariance_matrix)


Covariance Matrix:
[[250.  250.  125. ]
 [250.  250.  125. ]
 [125.  125.   62.5]]


In [8]:
import string
def is_palindrome(s):
    s = s.lower()
    s = ''.join(char for char in s if char not in string.punctuation and char != ' ')
    return s == s[::-1]
print(is_palindrome("radar")) 
print(is_palindrome("hello")) 

True
False


In [9]:
import numpy as np

identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Replace the last row with a sequence from 1 to 5
identity_matrix[4] = [1, 2, 3, 4, 5]

print("Modified 5x5 Identity Matrix:")
print(identity_matrix)

Modified 5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 2. 3. 4. 5.]]


In [11]:
import numpy as np

# Create the modified 5x5 identity matrix
identity_matrix = np.eye(5)
identity_matrix[-1] = [1, 2, 3, 4, 5]

# Calculate the sum of the diagonal elements
sum_diagonal = np.trace(identity_matrix)

print("Sum of diagonal elements:", sum_diagonal)


Sum of diagonal elements: 9.0


In [12]:
import numpy as np

# Create the modified 5x5 identity matrix
identity_matrix = np.eye(5)
identity_matrix[-1] = [1, 2, 3, 4, 5]

# Extract the second and fourth columns (indexing starts from 0)
second_column = identity_matrix[:, 1]
fourth_column = identity_matrix[:, 3]

# Sum their elements
sum_second_fourth_columns = np.sum(second_column) + np.sum(fourth_column)

print("Sum of elements in the second and fourth columns:", sum_second_fourth_columns)


Sum of elements in the second and fourth columns: 8.0


In [14]:
def convert_to_roman(num):
    if not isinstance(num, int) or num < 1 or num > 100:
        raise ValueError("Input must be an integer between 1 and 100")

    roman_numerals = {
        1: 'I', 4: 'IV', 5: 'V', 9: 'IX', 10: 'X', 
        40: 'XL', 50: 'L', 90: 'XC', 100: 'C'
    }

    result = ''
    for value, numeral in sorted(roman_numerals.items(), key=lambda x: x[0], reverse=True):
        while num >= value:
            result += numeral
            num -= value

    return result
# Example usage
print(convert_to_roman(5))    # Output: "V"
print(convert_to_roman(48))   # Output: "XLVIII"
print(convert_to_roman(89))   # Output: "LXXXIX"
print(convert_to_roman(100))  # Output: "C"


V
XLVIII
LXXXIX
C


In [15]:
# Edge cases (outside the range)
try:
    print(convert_to_roman(0))   # Should raise ValueError
except ValueError as e:
    print(e)  # Output: Input must be an integer between 1 and 100
    
try:
    print(convert_to_roman(150))  # Should raise ValueError
except ValueError as e:
    print(e)  # Output: Input must be an integer between 1 and 100

Input must be an integer between 1 and 100
Input must be an integer between 1 and 100
